/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

//import java.util.HashMap;
import java.util.ArrayList;

import javax.swing.JOptionPane;
import model.City;
import model.Community;
import model.Encounter;
import model.EncounterHistory;
import model.House;
import model.Patient;
import model.PatientDirectory;
import model.Person;
import model.PersonDirectory;
import model.VitalSigns;

/**
 *
 * @author Neha
 */
public class createJPanel extends javax.swing.JPanel {

    /**
     * Creates new form createJPanel
     */
    Person person1 ;
    Patient patient ;
    PersonDirectory persondirectory;
    PatientDirectory patientdirectory;
    ArrayList<Patient> patientHistory1;
    public createJPanel(Patient patient, PatientDirectory patientdirectory) {
      
        initComponents();
        lblMRN.setVisible(false);
        txtMRN.setVisible(false);
        this.patient=patient;
        this.patientdirectory=patientdirectory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblMobNo = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        txtMobileNumber = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblHouseNo = new javax.swing.JLabel();
        txtHouseNo = new javax.swing.JTextField();
        jComboBoxSalutation = new javax.swing.JComboBox<>();
        lblSalutation = new javax.swing.JLabel();
        lblSalutation1 = new javax.swing.JLabel();
        txtCommunity = new javax.swing.JTextField();
        lblCommunity = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblStreet = new javax.swing.JLabel();
        txtStreet = new javax.swing.JTextField();
        lblMRN = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();

        setBackground(new java.awt.Color(0, 153, 255));
        setForeground(new java.awt.Color(255, 255, 255));

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Patient");

        lblFirstName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name:");

        lblLastName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name:");

        lblAge.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblAge.setForeground(new java.awt.Color(255, 255, 255));
        lblAge.setText("Age:");

        lblMobNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMobNo.setForeground(new java.awt.Color(255, 255, 255));
        lblMobNo.setText("Mobile Number:");

        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyPressed(evt);
            }
        });

        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastNameKeyPressed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblHouseNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHouseNo.setForeground(new java.awt.Color(255, 255, 255));
        lblHouseNo.setText("House Number:");

        txtHouseNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHouseNoActionPerformed(evt);
            }
        });

        jComboBoxSalutation.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Miss.", "Mrs.", " " }));

        lblSalutation.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSalutation.setForeground(new java.awt.Color(255, 255, 255));
        lblSalutation.setText("Salutation");

        lblSalutation1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblSalutation1.setForeground(new java.awt.Color(255, 255, 255));
        lblSalutation1.setText("City:");

        txtCommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCommunityActionPerformed(evt);
            }
        });

        lblCommunity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblCommunity.setForeground(new java.awt.Color(255, 255, 255));
        lblCommunity.setText("Community:");

        txtCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCityActionPerformed(evt);
            }
        });

        lblHeight.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblHeight.setForeground(new java.awt.Color(255, 255, 255));
        lblHeight.setText("Height:");

        lblStreet.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblStreet.setForeground(new java.awt.Color(255, 255, 255));
        lblStreet.setText("Street:");

        txtStreet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStreetActionPerformed(evt);
            }
        });

        lblMRN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblMRN.setForeground(new java.awt.Color(255, 255, 255));
        lblMRN.setText("Medical Record Number:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblLastName)
                                            .addComponent(lblFirstName)
                                            .addComponent(lblAge)
                                            .addComponent(lblHeight))
                                        .addGap(131, 131, 131))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblSalutation1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblCommunity)
                                            .addComponent(lblStreet)
                                            .addComponent(lblMRN))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblMobNo)
                                    .addGap(105, 105, 105)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHouseNo)
                                .addGap(106, 106, 106)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(txtFirstName)
                                .addComponent(jComboBoxSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCommunity)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCity, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE)
                                .addComponent(txtHouseNo)
                                .addComponent(txtMobileNumber)
                                .addComponent(txtStreet))
                            .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(471, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {lblCommunity, lblSalutation1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSalutation, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFirstName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAge)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHeight)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobNo)
                    .addComponent(txtMobileNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHouseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHouseNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalutation1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCity, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStreet, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStreet, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCommunity)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtCommunity, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMRN))
                        .addGap(33, 33, 33)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblCommunity, lblSalutation1});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jComboBoxSalutation, txtAge, txtCity, txtCommunity, txtFirstName, txtHeight, txtHouseNo, txtLastName, txtMRN, txtMobileNumber, txtStreet});

    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    
    try{       
         
           int f= 1;
           //Person person = new Person();
           
           
          if((txtFirstName.getText().equals(null))||(txtFirstName.getText().trim().isEmpty())||!txtFirstName.getText().matches("^\\pL+[\\pL\\pZ\\pP]{0,}$")){
               JOptionPane.showMessageDialog(null,"Please enter a valid first name");   
               f=0;
        }
           
            if((txtLastName.getText().equals(null))||(txtLastName.getText().trim().isEmpty())){
                 JOptionPane.showMessageDialog(null,"Please enter a valid last name");   
                f=0;
          }
           
             if((txtAge.getText().equals(null))||(txtAge.getText().trim().isEmpty()) || !txtAge.getText().matches("\\b\\d+\\b")){
                 JOptionPane.showMessageDialog(null,"Please enter a valid age");   
                 f=0;
           }
           
          if((txtHeight.getText().equals(null))||(txtHeight.getText().trim().isEmpty())|| !txtHeight.getText().matches("([0-9]*[.]*[0-9])")){
                 JOptionPane.showMessageDialog(null,"Please enter a valid height");   
                 f=0;
           }
             
                 if((txtMobileNumber.getText().equals(null))||(txtMobileNumber.getText().trim().isEmpty()) || !txtMobileNumber.getText().matches("[0-9]{10}$")){
                 JOptionPane.showMessageDialog(null,"Please enter a valid 10 digit mobile number");   
                 f=0;
           } 
          
              if((txtHouseNo.getText().equals(null))||(txtHouseNo.getText().trim().isEmpty()) || !txtHouseNo.getText().matches("[0-9]+")){
                JOptionPane.showMessageDialog(null,"Please enter a valid house number");   
                 f=0;
           }
           
          if((txtCity.getText()==null)||(txtCity.getText().trim().isEmpty())|| !txtCity.getText().matches("^\\pL+[\\pL\\pZ\\pP]{0,}$")){
                JOptionPane.showMessageDialog(null,"Please enter a valid city name in alphabets");   
                f=0;
         } 
             
           if((txtStreet.getText()==null)||(txtStreet.getText().trim().isEmpty())){
               JOptionPane.showMessageDialog(null,"Please enter a valid street number");   
                f=0;
          }    
         
            
              if((txtCommunity.getText()==null)||(txtCommunity.getText().trim().isEmpty())|| !txtCommunity.getText().matches("^\\pL+[\\pL\\pZ\\pP]{0,}$")){
                 JOptionPane.showMessageDialog(null,"Please enter community name in alphabets");   
                 f=0;
           }     
             

        if(f==1){         
           Patient patient = new Patient();
           Encounter encounter = new Encounter();
           EncounterHistory encounterhistory = new EncounterHistory(); //EncounterHistory is a class with arraylist of                                                                            //Encounter 
           //PatientDirectory patientDirectory= new PatientDirectory();                                                                 
           ArrayList <Encounter> encounterList = new ArrayList<>();  //made a collection to push into encounterhistory
           //ArrayList<Patient> patients=new ArrayList<>(); //Its an arraylist of Patient to push into PatientDirectory
           Community community= new Community();
           City city = new City();
           VitalSigns vs= new VitalSigns();
           patient.setSalutation(jComboBoxSalutation.getSelectedItem().toString());
           
           
           
           patient.setFirstName(txtFirstName.getText());
           patient.setLastName(txtLastName.getText());
           patient.setAge(Integer.parseInt(txtAge.getText()));
           patient.setHeight(Double.parseDouble(txtHeight.getText()));
           patient.setMobileNo(txtMobileNumber.getText());
           House house= new House(txtHouseNo.getText());
           house.setStreetNo(txtStreet.getText());
           
           patient.setHouse(house);
           community.setCommunityName(txtCommunity.getText());
           patient.getHouse().setCommunity(community);
           Long uniqueNo = (long) Math.floor(Math.random() * 9000000000L);
           String MRN = "MR" + uniqueNo;
        
           patient.setMedicalRecordNumber(MRN);
           city.setCityName(txtCity.getText()); //setting city here
           house.setCity(city);
           community.setCity(city);
           patient.setHouse(house);
           vs.setBloodPressure(0);
           vs.setTemperature(0);
           vs.setPulse(0);
           encounter.setDate(null);
           encounter.setVitalsigns(vs);
           encounterList.add(encounter);
           encounterhistory.setEncounter(encounterList);
           patient.setEncounterhistory(encounterhistory); 
          // patientHistory1.add(patient); //patientHistory1 is my collection of Patient class
         
         
          //model.System.setPatientHistory(patientHistory1);
                
           patientdirectory.setPatientHistory(patient); 
           

         
              lblMRN.setVisible(true);
              txtMRN.setVisible(true); 
              txtMRN.setText(patient.getmedicalRecordNumber());
              JOptionPane.showMessageDialog(this,"Patient details added.");
           
          
        }
  
    } 
       catch(Exception e){
                  //JOptionPane.showMessageDialog(this, e.getMessage());        
            }
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtCommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCommunityActionPerformed

    private void txtCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCityActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtStreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStreetActionPerformed

    private void txtHouseNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHouseNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHouseNoActionPerformed

    private void txtFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyPressed
        // TODO add your handling code here:
        
     
    }//GEN-LAST:event_txtFirstNameKeyPressed

    private void txtLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> jComboBoxSalutation;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblCommunity;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHouseNo;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMRN;
    private javax.swing.JLabel lblMobNo;
    private javax.swing.JLabel lblSalutation;
    private javax.swing.JLabel lblSalutation1;
    private javax.swing.JLabel lblStreet;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtCommunity;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtHouseNo;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtMobileNumber;
    private javax.swing.JTextField txtStreet;
    // End of variables declaration//GEN-END:variables
}
