/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.Customer.Customer;
import Business.EcoSystem;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vijay
 */
public class ManageRestaurantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurantJPanel
     */
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccountDirectory userList;
    UserAccount user;
    public ManageRestaurantJPanel(UserAccount account, EcoSystem system) {
        initComponents();
         this.user=account;
        this.system=system;
        try{
        displayTable();}
        catch(Exception e){
            throw e;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurantContent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtRestaurantName = new javax.swing.JTextField();
        txtRestaurantLocation = new javax.swing.JTextField();
        txtRestaurantContact = new javax.swing.JTextField();
        txtRestaurantUsername = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtRestaurantPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Restaurant Information");

        tblRestaurantContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Restaurant Name", "Location", "Contact", "Username", "Password"
            }
        ));
        tblRestaurantContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRestaurantContentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRestaurantContent);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Location");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Contact Number:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Username");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Password");

        txtRestaurantLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRestaurantLocationActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Restaurant");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtRestaurantPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRestaurantPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtRestaurantName)
                            .addComponent(txtRestaurantLocation)
                            .addComponent(txtRestaurantContact)
                            .addComponent(txtRestaurantUsername)
                            .addComponent(txtRestaurantPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(63, 63, 63)
                                .addComponent(btnUpdate)
                                .addGap(72, 72, 72)
                                .addComponent(btnDelete))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(87, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRestaurantLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtRestaurantContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRestaurantUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtRestaurantPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnSave))
                .addContainerGap(72, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblRestaurantContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRestaurantContentMouseClicked
        // TODO add your handling code here:

        int rNum = tblRestaurantContent.getSelectedRow();
        Restaurant currentRestaurant= system.getRestaurantDirectory().getRestaurantList().get(rNum);
                
           
        txtRestaurantName.setText(tblRestaurantContent.getModel().getValueAt(rNum, 0).toString());
        txtRestaurantLocation.setText(tblRestaurantContent.getModel().getValueAt(rNum, 1).toString());
        txtRestaurantContact.setText(tblRestaurantContent.getModel().getValueAt(rNum, 2).toString());
        txtRestaurantUsername.setText(tblRestaurantContent.getModel().getValueAt(rNum, 3).toString());
        txtRestaurantPassword.setText(tblRestaurantContent.getModel().getValueAt(rNum, 4).toString());

    }//GEN-LAST:event_tblRestaurantContentMouseClicked

    private void txtRestaurantLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRestaurantLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRestaurantLocationActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if( txtRestaurantName.getText().isEmpty()||txtRestaurantLocation.getText().isEmpty()|| txtRestaurantContact.getText().isEmpty() || txtRestaurantUsername.getText().isEmpty() || txtRestaurantPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Fields cannot be empty");
            return;
        }
        if(system.getUserAccountDirectory().checkIfUsernameIsUnique(txtRestaurantUsername.getText())){

     Restaurant restaurant = new Restaurant(txtRestaurantUsername.getText(), txtRestaurantPassword.getText(),            txtRestaurantName.getText(),txtRestaurantLocation.getText(), txtRestaurantContact.getText());
                   
            system.getUserAccountDirectory().addUserAccount(restaurant);
            system.getRestaurantDirectory().createRestaurant(restaurant);

            displayTable();

            txtRestaurantName.setText("");
            txtRestaurantLocation.setText("");
            txtRestaurantContact.setText("");
            txtRestaurantUsername.setText("");
            txtRestaurantPassword.setText("");

        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int rNum = tblRestaurantContent.getSelectedRow();
        if(rNum<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }

        else {
            Restaurant deleteRestaurant = system.getRestaurantDirectory().getRestaurantList().get(rNum);
                   
            RestaurantDirectory restaurantDirectory = system.getRestaurantDirectory();
            restaurantDirectory.deleteRestaurant(deleteRestaurant);                  
            JOptionPane.showMessageDialog(null, "Restaurant"  + txtRestaurantName.getText() + "has been                       deleted");
            displayTable();
            txtRestaurantName.setText("");
            txtRestaurantLocation.setText("");
            txtRestaurantContact.setText("");
            txtRestaurantUsername.setText("");
            txtRestaurantPassword.setText("");
        }

    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int rNum= tblRestaurantContent.getSelectedRow();
        int flag=1;
        if(rNum<0){
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }
        if((txtRestaurantName.getText()==null)|| (txtRestaurantName.getText().trim().isEmpty())){
            JOptionPane.showMessageDialog(null,"Please enter a valid Restaurant Name");
            flag=0;
        }

        if((txtRestaurantLocation.getText()==null)|| (txtRestaurantLocation.getText().trim().isEmpty())){
            JOptionPane.showMessageDialog(null,"Please enter a valid Restaurant Location");
            flag=0;
        }

        if((txtRestaurantContact.getText()==null)|| (txtRestaurantContact.getText().trim().isEmpty())){
            JOptionPane.showMessageDialog(null,"Please enter a valid Restaurant Contact");
            flag=0;
        }

        if((txtRestaurantUsername.getText()==null)|| (txtRestaurantUsername.getText().trim().isEmpty())){
            JOptionPane.showMessageDialog(null,"Please enter a valid restaurant username");
            flag=0;
        }

        if(txtRestaurantPassword.getText()==null || (txtRestaurantPassword.getText().toString().trim().isEmpty())){
            JOptionPane.showMessageDialog(null,"Please enter a valid restaurant password");
            flag=0;
        }

        if(flag==1){
            Restaurant restaurantUpdate = system.getRestaurantDirectory().getRestaurantList().get(rNum);
                    
            
            restaurantUpdate.setRestaurantName(txtRestaurantName.getText());
                 
            restaurantUpdate.setLocation(txtRestaurantLocation.getText());
                  
            restaurantUpdate.setPhoneNumber(txtRestaurantContact.getText());
            
            restaurantUpdate.setUsername(txtRestaurantUsername.getText());
            restaurantUpdate.setPassword(txtRestaurantPassword.getText());
            system.getRestaurantDirectory().getRestaurantList().set(rNum, restaurantUpdate);
                  
            displayTable();
            
            txtRestaurantName.setText("");
            txtRestaurantLocation.setText("");
            txtRestaurantContact.setText("");
            txtRestaurantUsername.setText("");
            txtRestaurantPassword.setText("");
        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtRestaurantPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRestaurantPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRestaurantPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRestaurantContent;
    private javax.swing.JTextField txtRestaurantContact;
    private javax.swing.JTextField txtRestaurantLocation;
    private javax.swing.JTextField txtRestaurantName;
    private javax.swing.JTextField txtRestaurantPassword;
    private javax.swing.JTextField txtRestaurantUsername;
    // End of variables declaration//GEN-END:variables

    private void displayTable() {
        
        try{
        DefaultTableModel model = (DefaultTableModel) tblRestaurantContent.getModel();
        model.setRowCount(0);
        for (Restaurant r : system.getRestaurantDirectory().getRestaurantList()){
             Object[] row = new Object[5];
              
                    row[0] = r.getRestaurantName();
                    row[1] = r.getLocation();
                    row[2] = r.getPhoneNumber();
                    row[3] = r.getUsername();
                    row[4]= r.getPassword();
                    model.addRow(row);
                    
        }
    }
    catch(Exception e){
    throw e;
}

    }  }