/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.SystemAdminWorkArea;

import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.UserAccount.UserAccount;
import Business.UserAccount.UserAccountDirectory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vijay
 */
public class ManageDeliveryJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageDeliveryJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem system;
    UserAccountDirectory userList;
    UserAccount user;
    public ManageDeliveryJPanel(UserAccount account, EcoSystem system) {
        initComponents();
        
        this.user=user;
        this.system=system;
        displayTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDeliveryContent = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtDeliveryName = new javax.swing.JTextField();
        txtDeliveryContact = new javax.swing.JTextField();
        txtDeliveryNumberPlate = new javax.swing.JTextField();
        txtDeliveryUserName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtDeliveryPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Delivery Information");

        tblDeliveryContent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Contact", "Number Plate", "Username", "Password"
            }
        ));
        tblDeliveryContent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDeliveryContentMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDeliveryContent);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Contact Number:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Number Plate:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Username");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Password");

        txtDeliveryContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeliveryContactActionPerformed(evt);
            }
        });

        btnSave.setBackground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save Delivery Information");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete Delivery Information");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update Delivery Information");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtDeliveryPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeliveryPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(56, 56, 56)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDeliveryName)
                                    .addComponent(txtDeliveryContact)
                                    .addComponent(txtDeliveryNumberPlate)
                                    .addComponent(txtDeliveryUserName)
                                    .addComponent(txtDeliveryPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnSave)
                        .addGap(63, 63, 63)
                        .addComponent(btnUpdate)
                        .addGap(72, 72, 72)
                        .addComponent(btnDelete)))
                .addContainerGap(88, Short.MAX_VALUE))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDeliveryName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDeliveryContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDeliveryNumberPlate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDeliveryUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtDeliveryPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnSave))
                .addContainerGap(70, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblDeliveryContentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDeliveryContentMouseClicked
        // TODO add your handling code here:

        int rNum = tblDeliveryContent.getSelectedRow();
        DeliveryMan currentdelivery = system.getDeliveryManDirectory().getDeliveryList().get(rNum);
        txtDeliveryName.setText(tblDeliveryContent.getModel().getValueAt(rNum, 0).toString());
        txtDeliveryContact.setText(tblDeliveryContent.getModel().getValueAt(rNum, 1).toString());
        txtDeliveryNumberPlate.setText(tblDeliveryContent.getModel().getValueAt(rNum, 2).toString());
        txtDeliveryUserName.setText(tblDeliveryContent.getModel().getValueAt(rNum, 3).toString());
        txtDeliveryPassword.setText(tblDeliveryContent.getModel().getValueAt(rNum, 4).toString());
    }//GEN-LAST:event_tblDeliveryContentMouseClicked

    private void txtDeliveryContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeliveryContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeliveryContactActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:

        if( txtDeliveryName.getText().isEmpty()||txtDeliveryContact.getText().isEmpty()|| txtDeliveryNumberPlate.getText().isEmpty() || txtDeliveryUserName.getText().isEmpty() || txtDeliveryPassword.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Fields cannot be empty");
            return;
        }
        if(system.getUserAccountDirectory().checkIfUsernameIsUnique(txtDeliveryUserName.getText())){
            DeliveryMan addDelivery = new DeliveryMan(txtDeliveryUserName.getText(), txtDeliveryPassword.getText(), txtDeliveryName.getText(), txtDeliveryContact.getText(), txtDeliveryNumberPlate.getText());

            system.getUserAccountDirectory().addUserAccount(addDelivery);
            system.getDeliveryManDirectory().createDeliveryMan(addDelivery);

            displayTable();

            txtDeliveryName.setText("");
            txtDeliveryContact.setText("");
            txtDeliveryNumberPlate.setText("");
            txtDeliveryUserName.setText("");
            txtDeliveryPassword.setText("");

        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:

        int rNum = tblDeliveryContent.getSelectedRow();
        if(rNum<0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }

        else {
            DeliveryMan deleteDelivery = system.getDeliveryManDirectory().getDeliveryList().get(rNum);
            
            
            DeliveryManDirectory deliveryDirectory = system.getDeliveryManDirectory();
            deliveryDirectory.removeDeliveryMan(deleteDelivery);
     
            JOptionPane.showMessageDialog(null, "Delivery Man  "  + txtDeliveryUserName.getText() + " has been deleted");
            displayTable();
            txtDeliveryName.setText("");
            txtDeliveryContact.setText("");
            txtDeliveryNumberPlate.setText("");
            txtDeliveryUserName.setText("");
            txtDeliveryPassword.setText("");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int rNum= tblDeliveryContent.getSelectedRow();
        int flag=1;
        if(rNum<0){
            JOptionPane.showMessageDialog(this, "Please select a row to update");
            return;
        }
        if((txtDeliveryName.getText()==null)|| (txtDeliveryName.getText().trim().isEmpty())){
            JOptionPane.showMessageDialog(null,"Please enter a valid Delivery Name");
            flag=0;
        }

        if((txtDeliveryContact.getText()==null)|| (txtDeliveryContact.getText().trim().isEmpty())){
            JOptionPane.showMessageDialog(null,"Please enter a valid Delivery Contact");
            flag=0;
        }

        if((txtDeliveryNumberPlate.getText()==null)|| (txtDeliveryNumberPlate.getText().trim().isEmpty())){
            JOptionPane.showMessageDialog(null,"Please enter a valid Delivery Number Plate");
            flag=0;
        }

        if((txtDeliveryUserName.getText()==null)|| (txtDeliveryUserName.getText().trim().isEmpty())){
            JOptionPane.showMessageDialog(null,"Please enter a valid Delivery User Name");
            flag=0;
        }

        if(txtDeliveryPassword.getText()==null || (txtDeliveryPassword.getText().toString().trim().isEmpty())){
             JOptionPane.showMessageDialog(null,"Please enter a valid Password");
            flag=0;
         
        }

        if(flag==1){
            DeliveryMan deliveryUpdate = system.getDeliveryManDirectory().getDeliveryList().get(rNum);
            deliveryUpdate.setDeliveryName(txtDeliveryName.getText());
        
   
            deliveryUpdate.setPhone(txtDeliveryContact.getText());
       
           deliveryUpdate.setNamePlate(txtDeliveryNumberPlate.getText());
            deliveryUpdate.setUsername(txtDeliveryUserName.getText());
            deliveryUpdate.setPassword(txtDeliveryPassword.getText());
            system.getDeliveryManDirectory().getDeliveryList().set(rNum,deliveryUpdate);
            displayTable();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txtDeliveryPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeliveryPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeliveryPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDeliveryContent;
    private javax.swing.JTextField txtDeliveryContact;
    private javax.swing.JTextField txtDeliveryName;
    private javax.swing.JTextField txtDeliveryNumberPlate;
    private javax.swing.JTextField txtDeliveryPassword;
    private javax.swing.JTextField txtDeliveryUserName;
    // End of variables declaration//GEN-END:variables

    private void displayTable() {
            
        DefaultTableModel model = (DefaultTableModel) tblDeliveryContent.getModel();
        model.setRowCount(0);
        for (DeliveryMan d : system.getDeliveryManDirectory().getDeliveryList()){
             Object[] row = new Object[5];
              
                    row[0] = d.getDeliveryName();
                    row[1] = d.getPhone();
                    row[2] = d.getNamePlate();
                    row[3] = d.getUsername();
                    row[4]= d.getPassword();
                    model.addRow(row);
                    
        }
        
        
    }
}
