/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.UberCar;
import model.UberList;

/**
 *
 * @author Neha
 */
public class Search extends javax.swing.JPanel {

    /**
     * Creates new form Search
     */
    UberList cars;
    UberCar selectCar;
    UberCar firstAvailCar;
    int availCars=0,notavailCars=0;
    public Search(UberList cars) {
        initComponents();
        this.cars=cars;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        lblPassengerCar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchCar = new javax.swing.JTable();
        btnfirstPassCar = new javax.swing.JButton();
        btnAvailCars = new javax.swing.JButton();
        btnUnavailCars = new javax.swing.JButton();
        lblAvail = new java.awt.Label();
        lblNotAvail = new java.awt.Label();
        jTextField2 = new javax.swing.JTextField();
        carsByModelComboBox = new javax.swing.JComboBox<>();
        btnModelNo = new javax.swing.JButton();
        lblByModelNo = new javax.swing.JLabel();
        lblBySerialNo = new javax.swing.JLabel();
        txtFindBySerial = new javax.swing.JTextField();
        btnFindBySerialNo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtManuYear = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        minComboBox = new javax.swing.JComboBox<>();
        maxComboBox = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextField1.setText("  SEARCH");

        lblPassengerCar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPassengerCar.setText("Display passenger details:");

        tblSearchCar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Car Name", "Car Manufacturer", "Passenger Car Availability", "Car Availability", "Manufacturer Year", "No. Of Seats", "Serial Number", "Model Number", "Maintenance Certificate Date", "Car Available in Cities"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSearchCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchCarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSearchCar);

        btnfirstPassCar.setText("First Available Car");
        btnfirstPassCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfirstPassCarActionPerformed(evt);
            }
        });

        btnAvailCars.setText("Available Cars");
        btnAvailCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailCarsActionPerformed(evt);
            }
        });

        btnUnavailCars.setText("Unavailable Cars");
        btnUnavailCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUnavailCarsActionPerformed(evt);
            }
        });

        lblAvail.setText("label1");

        lblNotAvail.setText("label2");

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Total Count: ");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        carsByModelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "VX", "SUV", "HatchBack", "VI" }));
        carsByModelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carsByModelComboBoxActionPerformed(evt);
            }
        });

        btnModelNo.setText("Find By Model No");
        btnModelNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelNoActionPerformed(evt);
            }
        });

        lblByModelNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblByModelNo.setText("Display car details by model number:");

        lblBySerialNo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblBySerialNo.setText("Display cars details by serial number:");

        btnFindBySerialNo.setText("Find By Serial No");
        btnFindBySerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindBySerialNoActionPerformed(evt);
            }
        });

        jButton1.setText("Find By Manufacture Year");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Display by manufacture year:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Display Cars between minimum and maximum seats: ");

        minComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        maxComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7" }));

        jButton2.setText("Display Cars");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblPassengerCar, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnfirstPassCar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnAvailCars)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUnavailCars))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblBySerialNo)
                                        .addGap(6, 6, 6)
                                        .addComponent(txtFindBySerial, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(66, 66, 66)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lblNotAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(54, 54, 54))
                                    .addComponent(btnFindBySerialNo))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(minComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(maxComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblByModelNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(carsByModelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModelNo)))))
                .addGap(0, 116, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassengerCar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfirstPassCar)
                    .addComponent(btnAvailCars)
                    .addComponent(btnUnavailCars))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNotAvail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBySerialNo)
                    .addComponent(txtFindBySerial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindBySerialNo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtManuYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblByModelNo)
                    .addComponent(carsByModelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModelNo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(minComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblSearchCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchCarMouseClicked
        // TODO add your handling code here:
//        int rowNumber=tblCars.getSelectedRow();
//
//        UberCar car= cars.getCars().get(rowNumber);
//        txtCarName.setText(car.getCarName());
//        txtCarManufacturer.setText(car.getCarManufacture());
//        txtNoOfSeats.setText(String.valueOf(car.getNoOfSeats()));
//        txtSerialNo.setText(String.valueOf(String.valueOf(car.getSerialNumber())));
//        String passCar=car.getIsPassengerCarAvailable();
//        if(passCar.equalsIgnoreCase("Yes")){
//            yesPassengerRadioButton.setSelected(true);
//        }
//        else{
//            noPassengerRadioButton.setSelected(true);
//        }
//
//        String carAvail=car.getCarAvailability();
//
//        if(carAvail.equalsIgnoreCase("yes")){
//            availabilityYes.setSelected(true);
//        }
//        else
//        availabilityNo.setSelected(true);
//
//        jYearChooser.setYear(car.getManufactureYear());
//        JDateExp.setDate(car.getMaintenanceCertDate());
//
//        modelComboBox.setSelectedItem(car.getModelNumber());
//
//        for(String city: car.getAvailableCities()){
//            if(city.equalsIgnoreCase("Boston"))
//            BostonCheckBox.setSelected(true);
//            else if(city.equalsIgnoreCase("New Jersey"))
//            NewJerseyCheckBox.setSelected(true);
//
//            else if(city.equalsIgnoreCase("Dallas"))
//            DallasCheckBox.setSelected(true);
//            else
//            OregonCheckBox.setSelected(true);
//        }

    }//GEN-LAST:event_tblSearchCarMouseClicked

    private void btnfirstPassCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfirstPassCarActionPerformed
        // TODO add your handling code here:
        List<UberCar>z=new ArrayList<>();
        for(UberCar uCar:cars.getCars()){
            if(uCar.getIsPassengerCarAvailable().equalsIgnoreCase("Yes")){
                z.add(uCar);
            addToTable(z);
            return;
            }
        }
        
    }//GEN-LAST:event_btnfirstPassCarActionPerformed

    private void btnAvailCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailCarsActionPerformed
        // TODO add your handling code here:
        List<UberCar>lstCar=new ArrayList<>();
        for(UberCar uCar:cars.getCars()){
            if(uCar.getCarAvailability().equalsIgnoreCase("Yes")){
                lstCar.add(uCar);
                //availCars++;
                addToTable(lstCar);
                
            }
            lblAvail.setText(String.valueOf(lstCar.size()));
        }
        
    }//GEN-LAST:event_btnAvailCarsActionPerformed

    private void btnUnavailCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUnavailCarsActionPerformed
        // TODO add your handling code here:
        List<UberCar>lstCar=new ArrayList<>();
        for(UberCar uCar:cars.getCars()){
            if(uCar.getCarAvailability().equalsIgnoreCase("No")){
                lstCar.add(uCar);
                
                addToTable(lstCar);
            }  
            lblNotAvail.setText(String.valueOf(lstCar.size()));
        }
    }//GEN-LAST:event_btnUnavailCarsActionPerformed

    
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void carsByModelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carsByModelComboBoxActionPerformed
        // TODO add your handling code here:
        //String select= carsByModelComboBox.getSelectedItem().toString();
    }//GEN-LAST:event_carsByModelComboBoxActionPerformed

    private void btnModelNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelNoActionPerformed
        // TODO add your handling code here:
        List<UberCar>z=new ArrayList<>();
        for(UberCar uCar:cars.getCars()){
        if(uCar.getModelNumber().equalsIgnoreCase(carsByModelComboBox.getSelectedItem().        
                toString())){
                z.add(uCar);
                addToTable(z);
        }        
    }//GEN-LAST:event_btnModelNoActionPerformed
    }
    private void btnFindBySerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindBySerialNoActionPerformed
        // TODO add your handling code here:
        
        List<UberCar>z=new ArrayList<>();
        for(UberCar uCar:cars.getCars()){
            if(String.valueOf(uCar.getSerialNumber()).equals(txtFindBySerial.getText())){
                 z.add(uCar);
                 addToTable(z);
            }
        }
        
    }//GEN-LAST:event_btnFindBySerialNoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        List<UberCar>z=new ArrayList<>();
         for(UberCar uCar:cars.getCars()){
            if(String.valueOf(uCar.getManufactureYear()).equals(txtManuYear.getText())){
                 z.add(uCar);
                 addToTable(z);
            }
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        List<UberCar>z=new ArrayList<>();
        for(UberCar uCar:cars.getCars()){
        
         
        Integer max=(Integer.valueOf((String)maxComboBox.getSelectedItem()));
        Integer min=(Integer.valueOf((String)minComboBox.getSelectedItem()));
        if(uCar.getNoOfSeats()>=min && uCar.getNoOfSeats()<=max){
            z.add(uCar);
            addToTable(z);
        }
            
    }//GEN-LAST:event_jButton2ActionPerformed
   }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAvailCars;
    private javax.swing.JButton btnFindBySerialNo;
    private javax.swing.JButton btnModelNo;
    private javax.swing.JButton btnUnavailCars;
    private javax.swing.JButton btnfirstPassCar;
    private javax.swing.JComboBox<String> carsByModelComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private java.awt.Label lblAvail;
    private javax.swing.JLabel lblByModelNo;
    private javax.swing.JLabel lblBySerialNo;
    private java.awt.Label lblNotAvail;
    private javax.swing.JLabel lblPassengerCar;
    private javax.swing.JComboBox<String> maxComboBox;
    private javax.swing.JComboBox<String> minComboBox;
    private javax.swing.JTable tblSearchCar;
    private javax.swing.JTextField txtFindBySerial;
    private javax.swing.JTextField txtManuYear;
    // End of variables declaration//GEN-END:variables

    private void addToTable(List<UberCar> listCars) {
            DefaultTableModel model = (DefaultTableModel)tblSearchCar.getModel();
            model.setRowCount(0);
          for(UberCar car1: listCars){
            Object[] row= new Object[10];
            row[0]=car1.getCarName();
            row[1]=car1.getCarManufacture();
            row[2]=car1.getIsPassengerCarAvailable();
            row[3]=car1.getCarAvailability();
            row[4]=car1.getManufactureYear();
            row[5]=car1.getNoOfSeats();
            row[6]=car1.getSerialNumber();
            row[7]=car1.getModelNumber();
            row[8]=car1.getMaintenanceCertDate();
            row[9]=car1.getAvailableCities();
            model.addRow(row);
    }
 }
}
