/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.io.File;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JLabel;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.Person;

/**
 *
 * @author Neha
 */
public class PersonCreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Person person;
    public PersonCreateJPanel(Person person) {
        this.person=person;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblGeogDate = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        lblTelNo = new javax.swing.JLabel();
        txtGeogData = new javax.swing.JTextField();
        txtPrimaryNo = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblEmailID = new javax.swing.JLabel();
        lbSSN = new javax.swing.JLabel();
        lblMRN = new javax.swing.JLabel();
        lblHealthPlanID = new javax.swing.JLabel();
        lblAccountNumber = new javax.swing.JLabel();
        txtMRN = new javax.swing.JTextField();
        txtPrimaryEmailID = new javax.swing.JTextField();
        txtCert_LicenceNo = new javax.swing.JTextField();
        txtPrimaryAccountNumber = new javax.swing.JTextField();
        txtSSN = new javax.swing.JTextField();
        lblCert_LicenceNo = new javax.swing.JLabel();
        lblVehicleIden_SerialNo = new javax.swing.JLabel();
        lblDeviceIdenNumber = new javax.swing.JLabel();
        lblLinkedin = new javax.swing.JLabel();
        lblIPAddr = new javax.swing.JLabel();
        lblIdentifierNo = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLinkedin = new javax.swing.JTextField();
        txtDeviceIdenNumber = new javax.swing.JTextField();
        txtVehicleIden_SerialNo = new javax.swing.JTextField();
        txtHealthPlanID = new javax.swing.JTextField();
        txtIPAddr1 = new javax.swing.JTextField();
        txtIdentifierNo = new javax.swing.JTextField();
        txtSecondaryNo = new javax.swing.JTextField();
        txtSecondaryEmailID = new javax.swing.JTextField();
        txtDeviceIdenNumber2 = new javax.swing.JTextField();
        txtIPAddr2 = new javax.swing.JTextField();
        txtSecondaryAccountNumber = new javax.swing.JTextField();
        btnUploadImage = new javax.swing.JButton();
        btnUploadBiometrics = new javax.swing.JButton();
        txtLastName = new javax.swing.JTextField();
        lblFax = new javax.swing.JLabel();
        txtFax = new javax.swing.JTextField();
        txtDOB = new com.toedter.calendar.JDateChooser();

        lblTitle.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create");

        lblName.setText("Name:");

        lblGeogDate.setText("Geographic Data:");

        lblDOB.setText("Date of Birth:");

        lblTelNo.setText("Telephone numbers (Primary/Secondary):");

        txtGeogData.setToolTipText("Enter your address");
        txtGeogData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGeogDataActionPerformed(evt);
            }
        });

        txtPrimaryNo.setToolTipText("Enter your primary telephone number (xxx-xxx-xxxx)");
        txtPrimaryNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimaryNoActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        lblEmailID.setText("Email ID (Primary/Secondary):");

        lbSSN.setText("SSN:");

        lblMRN.setText("Medical Record Number:");

        lblHealthPlanID.setText("Health Plan ID:");

        lblAccountNumber.setText("Account number (Primary/Secondary):");

        txtMRN.setToolTipText("Enter 7 digit Medical Record Number");
        txtMRN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMRNActionPerformed(evt);
            }
        });

        txtPrimaryEmailID.setToolTipText("Enter your primary email address");
        txtPrimaryEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimaryEmailIDActionPerformed(evt);
            }
        });

        txtCert_LicenceNo.setToolTipText("Enter alphanumeric certificate number");
        txtCert_LicenceNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCert_LicenceNoActionPerformed(evt);
            }
        });

        txtPrimaryAccountNumber.setToolTipText("Enter 9 digit primary account number");
        txtPrimaryAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrimaryAccountNumberActionPerformed(evt);
            }
        });

        txtSSN.setToolTipText("Enter 9 digit SSN number");
        txtSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSSNActionPerformed(evt);
            }
        });

        lblCert_LicenceNo.setText("Certificate/License number:");

        lblVehicleIden_SerialNo.setText("Vehicle Identifier/ Serial number:");

        lblDeviceIdenNumber.setText("Device Identifier numbers:");

        lblLinkedin.setText("Linkedin:");

        lblIPAddr.setText("IP address:");

        lblIdentifierNo.setText("Unique Identifier Number:");

        txtFirstName.setToolTipText("Enter your first name");
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });

        txtLinkedin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLinkedinActionPerformed(evt);
            }
        });

        txtDeviceIdenNumber.setToolTipText("Enter 12 digit alphanumeric device identifier number");
        txtDeviceIdenNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceIdenNumberActionPerformed(evt);
            }
        });

        txtVehicleIden_SerialNo.setToolTipText("Enter alphanumeric vehicle/serial number");
        txtVehicleIden_SerialNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVehicleIden_SerialNoActionPerformed(evt);
            }
        });

        txtHealthPlanID.setToolTipText("Enter alphanumeric health plan ID");
        txtHealthPlanID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHealthPlanIDActionPerformed(evt);
            }
        });

        txtIPAddr1.setToolTipText("Enter the primary IP address");
        txtIPAddr1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddr1ActionPerformed(evt);
            }
        });

        txtIdentifierNo.setToolTipText("Enter alphanumeric unique identifier number");
        txtIdentifierNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentifierNoActionPerformed(evt);
            }
        });

        txtSecondaryNo.setToolTipText("Enter your secondary telephone number (xxx-xxx-xxxx)");
        txtSecondaryNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecondaryNoActionPerformed(evt);
            }
        });

        txtSecondaryEmailID.setToolTipText("Enter your secondary email address");
        txtSecondaryEmailID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecondaryEmailIDActionPerformed(evt);
            }
        });

        txtDeviceIdenNumber2.setToolTipText("Enter 12 digit alphanumeric device identifier number");
        txtDeviceIdenNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeviceIdenNumber2ActionPerformed(evt);
            }
        });

        txtIPAddr2.setToolTipText("Enter the secondary IP address");
        txtIPAddr2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPAddr2ActionPerformed(evt);
            }
        });

        txtSecondaryAccountNumber.setToolTipText("Enter 9 digit secondary account number");
        txtSecondaryAccountNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecondaryAccountNumberActionPerformed(evt);
            }
        });

        btnUploadImage.setText("Upload Image");
        btnUploadImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadImageActionPerformed(evt);
            }
        });

        btnUploadBiometrics.setText("Upload Biometrics");
        btnUploadBiometrics.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadBiometricsActionPerformed(evt);
            }
        });

        txtLastName.setToolTipText("Enter your last name");
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });

        lblFax.setText("Fax:");

        txtFax.setToolTipText("Enter digits greater than 6 for fax number");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGeogDate)
                            .addComponent(lblDOB)
                            .addComponent(lblName)
                            .addComponent(lblFax)
                            .addComponent(lblTelNo)
                            .addComponent(lblEmailID)
                            .addComponent(lbSSN)
                            .addComponent(lblMRN)
                            .addComponent(lblHealthPlanID)
                            .addComponent(lblAccountNumber)
                            .addComponent(lblCert_LicenceNo)
                            .addComponent(lblVehicleIden_SerialNo)
                            .addComponent(lblLinkedin)
                            .addComponent(lblIPAddr)
                            .addComponent(lblIdentifierNo)
                            .addComponent(lblDeviceIdenNumber))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtVehicleIden_SerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCert_LicenceNo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGeogData, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPrimaryNo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSecondaryNo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPrimaryEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSecondaryEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtHealthPlanID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtPrimaryAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSecondaryAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtIPAddr1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtIPAddr2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtIdentifierNo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtDeviceIdenNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtDeviceIdenNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnUploadImage)
                        .addGap(18, 18, 18)
                        .addComponent(btnUploadBiometrics)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitle)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGeogDate)
                    .addComponent(txtGeogData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblDOB))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFax)
                    .addComponent(txtFax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrimaryNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSecondaryNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailID)
                    .addComponent(txtPrimaryEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSecondaryEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSSN)
                    .addComponent(txtSSN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblMRN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtMRN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHealthPlanID)
                    .addComponent(txtHealthPlanID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAccountNumber)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPrimaryAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSecondaryAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCert_LicenceNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtCert_LicenceNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVehicleIden_SerialNo)
                    .addComponent(txtVehicleIden_SerialNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLinkedin)
                    .addComponent(txtLinkedin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIPAddr)
                    .addComponent(txtIPAddr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIPAddr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentifierNo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdentifierNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeviceIdenNumber)
                    .addComponent(txtDeviceIdenNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDeviceIdenNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUploadImage)
                    .addComponent(btnUploadBiometrics))
                .addGap(13, 13, 13)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 707, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtHealthPlanIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHealthPlanIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHealthPlanIDActionPerformed

    private void txtVehicleIden_SerialNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVehicleIden_SerialNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVehicleIden_SerialNoActionPerformed

    private void txtDeviceIdenNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceIdenNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdenNumberActionPerformed

    private void txtLinkedinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLinkedinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLinkedinActionPerformed

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSSNActionPerformed

    private void txtPrimaryAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimaryAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimaryAccountNumberActionPerformed

    private void txtCert_LicenceNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCert_LicenceNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCert_LicenceNoActionPerformed

    private void txtPrimaryEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimaryEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimaryEmailIDActionPerformed

    private void txtMRNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMRNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMRNActionPerformed

    
    
    //Button Save
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        int flag=1;
        // TODO add your handling code here:
        
        /*VALIDATIONS*/
        
        //validations for name, trim will remove all empty spaces and then check if its empty.
        //null we include to avoid null pointer exceptions.
        
      if((txtFirstName.getText()==null) || (txtFirstName.getText().trim().isEmpty()) || (!txtFirstName.getText().matches("^[a-zA-Z]*$"))
           ||
          ((txtLastName.getText()==null))||(txtLastName.getText().trim().isEmpty()) || (!txtLastName.getText().matches("^[a-zA-Z]*$")))
          
      {
          
          JOptionPane.showMessageDialog(null,"Please enter a valid complete name");   
          flag=0;
          
      }  
      
      //validation for geog data to ensure its not null or has spaces.
      
      if(txtGeogData.getText()==null || txtGeogData.getText().trim().isEmpty()){
         
        JOptionPane.showMessageDialog(null,"Please enter a valid geographical address"); 
        flag=0;
      }
      
      //primary mobile number in this format ^\d{3}-\d{3}-\d{4}$ eg:456-789-9999
        if((txtPrimaryNo.getText()==null)|| (txtPrimaryNo.getText().trim().isEmpty()) || !(txtPrimaryNo.                    getText().matches("^\\d{3}-\\d{3}-\\d{4}$")))
        {
            
            JOptionPane.showMessageDialog(null,"Please enter a valid primary mobile number in xxx-xxx-xxxx"+                      "format"); 
            flag=0;
        }
        
        //secondary mobile number in this format ^\d{3}-\d{3}-\d{4}$ eg:456-789-9999
        if((txtSecondaryNo.getText()==null)|| (txtSecondaryNo.getText().trim().isEmpty())|| !(txtSecondaryNo.               getText().matches("^\\d{3}-\\d{3}-\\d{4}$")))
        {
            
            JOptionPane.showMessageDialog(null,"Please enter a valid secondary mobile number in xxx-xxx-xxxx   "
                    + "format");
            flag=0;
        }
        
        // validation for fax number
        
        if((txtFax.getText()==null)|| (txtFax.getText().trim().isEmpty())||
                !(txtFax.getText().matches("^\\+?[0-9]{6,}$"))){
            
            JOptionPane.showMessageDialog(null, "Please enter a valid FAX number "
                    + "starting with atleast 6 digits");
            flag=0;
        }
        
        //email addresses should contain @ and .com and not be blank or have spaces.
        if( (txtPrimaryEmailID.getText()==null) || (txtPrimaryEmailID.getText().trim().isEmpty()) ||!                           (txtPrimaryEmailID.getText().contains(".com") && txtPrimaryEmailID.getText().contains("@"))){
            
            JOptionPane.showMessageDialog(null,"Please enter a valid primary Email ID");     
            flag=0;
        }
        //email addresses should contain @ and .com and not be blank or have spaces.
        if((txtSecondaryEmailID.getText()==null) || (txtSecondaryEmailID.getText().trim().isEmpty()) || !       (               txtSecondaryEmailID.getText().contains(".com") && txtSecondaryEmailID.getText().contains("@"))){
            
            JOptionPane.showMessageDialog(null,"Please enter a valid secondary Email ID");
            flag=0;
        }
        
        // SSN validation with no blanks, spaces and can contain only digits 0 to 9 and 9 digit number.
        if( (txtSSN.getText()==null)|| (txtSSN.getText().trim().isEmpty())||
                !(txtSSN.getText().matches("^[0-9]{9}$")) &&((txtSSN.getText()).length()!=9)){
            
            
            JOptionPane.showMessageDialog(null,"Please enter a 9 digit SSN number");
            flag=0;
        }
                
         //MRN validation with no blanks, spaces and can contain alpha numeric with no special characters
        if((txtMRN.getText()==null) || (txtMRN.getText().trim().isEmpty()) ||
                !(txtMRN.getText().matches("^[0-9]{7}+$"))) {
            
            JOptionPane.showMessageDialog(null,"Please enter a valid 7 digit Medical Record Number");
            flag=0;
        } 
        
        //Health plan ID validation with no blanks, spaces and can contain alpha numeric with no special                 characters
        if((txtHealthPlanID.getText()==null) || (txtHealthPlanID.getText().trim().isEmpty())
            ||!(txtHealthPlanID.getText().matches("^[a-zA-Z0-9]+$"))){
            
            JOptionPane.showMessageDialog(null,"Please enter a valid Health Plan ID");
            flag=0;
        }
        
        //Primary account number validation with no blanks, spaces and can contain numbers with no special           characters
        if((txtPrimaryAccountNumber.getText()==null) ||(txtPrimaryAccountNumber.getText().trim().isEmpty())
                || !(txtPrimaryAccountNumber.getText().matches("^[0-9]{9}$"))){
            
            
            JOptionPane.showMessageDialog(null,"Please enter a valid 9 digit primary account number");
            flag=0;
        }
        
        //Secondary account number validation with no blanks, spaces and can contain numbers with no                 special characters
        
        if((txtSecondaryAccountNumber.getText()==null) ||(txtSecondaryAccountNumber.getText().trim().isEmpty())
                || !(txtSecondaryAccountNumber.getText().matches("^[0-9]{9}$"))){
            
            
            JOptionPane.showMessageDialog(null,"Please enter a valid 9 digit secondary account number");
            flag=0;
        }
        
        //License number is alphanumeric with no special characters.
       
        if((txtCert_LicenceNo.getText()==null) ||(txtCert_LicenceNo.getText().trim().isEmpty())
            || !(txtCert_LicenceNo.getText().matches("^[a-zA-Z0-9]+$"))){
            
            JOptionPane.showMessageDialog(null,"Please enter valid Certificate/License Number");
            flag=0;
        }
        
        // txtVehicleIden_SerialNo is alphanumeric with no special characters.
        
        if((txtVehicleIden_SerialNo.getText()==null) || (txtVehicleIden_SerialNo.getText().trim().isEmpty())
                || !(txtVehicleIden_SerialNo.getText().matches("^[a-zA-Z0-9]+$"))){
            
            JOptionPane.showMessageDialog(null,"Please enter a valid Vehicle Identification Number");
            flag=0;
        }
         
        //txtDeviceIdenNumber1 is alphanumeric with no special characters which is 12 digit.
        if((txtDeviceIdenNumber.getText()==null) || (txtDeviceIdenNumber.getText().trim().isEmpty())
                ||(!txtDeviceIdenNumber.getText().matches("^[0-9]{12}$"))){
            flag=0;
            JOptionPane.showMessageDialog(null, "Please enter a valid 12 digit Device Identifier Number "
                    + "only between digits.");
                 
        }
        
        //DeviceIdenNumber2 alphanumeric with no special characters which is 12 digit.
        if((txtDeviceIdenNumber2.getText()==null) || (txtDeviceIdenNumber2.getText().trim().isEmpty())
                || !(txtDeviceIdenNumber2.getText().matches("^[0-9]{12}$"))){
            flag=0;
            JOptionPane.showMessageDialog(null, "Please enter a valid 12 digit Device Identifier Number 2 "
                    + "only between digits.");
            
        }
        
        //linkedin url validation, not null and contains a particular value
        if((txtLinkedin.getText()==null) || (txtLinkedin.getText().trim().isEmpty()) || !                                   txtLinkedin.getText().startsWith("http://www.linkedin.com/in/")){
                flag=0;
                JOptionPane.showMessageDialog(null, "Please enter a valid Linkedin Url in http://www.linkedin."+"com/in/ format");
            
                }
        
        //alpha numeric unique identification number and also not null.
        if((txtIdentifierNo.getText()==null) || (txtIdentifierNo.getText().trim().isEmpty())
                || !(txtIdentifierNo.getText().matches("^[a-zA-Z0-9]+$"))){
                flag=0;
                JOptionPane.showMessageDialog(null, "Please enter a Unique Idendifier Number");
        }
        
        
        try {
            person.setDOB(txtDOB.getDate());
        } catch (ParseException ex) {
            Logger.getLogger(PersonCreateJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
          
       // To set the values if it satisfies the validations.
        person.setFirstName(txtFirstName.getText()); //done
        
        person.setLastName(txtLastName.getText());  //done
        
        person.setGeogData(txtGeogData.getText()); //done
        person.setprimaryTelNo(txtPrimaryNo.getText()); //done
        person.setsecondaryTelNo(txtSecondaryNo.getText()); //done
        
        person.setFaxNo(txtFax.getText()); //done
        person.setPrimaryEmailID(txtPrimaryEmailID.getText());//done
        person.setSecondaryEmailID(txtSecondaryEmailID.getText()); //done
        person.setSSN(txtSSN.getText());  //done
        person.setMRN(txtMRN.getText());//done
        person.setHealthPlanID(txtHealthPlanID.getText()); //done
        person.setPrimaryAccNumber(txtPrimaryAccountNumber.getText()); //done
        person.setSecondaryAccNumber(txtSecondaryAccountNumber.getText()); //done
        person.setCert_licenseNumber(txtCert_LicenceNo.getText()); //done
        
        person.setVehicleIdentifier(txtVehicleIden_SerialNo.getText());
        person.setDeviceIdentifier1(txtDeviceIdenNumber.getText()); //done
        person.setDeviceIdentifier2(txtDeviceIdenNumber2.getText()); //done
        person.setlinkedinUrl(txtLinkedin.getText()); //done
        
        //no validation for IP address.
        person.setIPaddr1(txtIPAddr1.getText());
        person.setIPaddr2(txtIPAddr2.getText());
        
        //for unique identification number
        person.setUniqueIdentifier(txtIdentifierNo.getText()); //done
        
     
        if(flag==1){                 
            JOptionPane.showMessageDialog(this, "Person Information Saved");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtPrimaryNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrimaryNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrimaryNoActionPerformed

    private void txtGeogDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGeogDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGeogDataActionPerformed

    private void txtIPAddr1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddr1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddr1ActionPerformed

    private void txtIdentifierNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentifierNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentifierNoActionPerformed

    private void txtSecondaryNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecondaryNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecondaryNoActionPerformed

    private void txtSecondaryEmailIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecondaryEmailIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecondaryEmailIDActionPerformed

    private void txtDeviceIdenNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeviceIdenNumber2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDeviceIdenNumber2ActionPerformed

    private void txtIPAddr2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPAddr2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPAddr2ActionPerformed

    private void txtSecondaryAccountNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecondaryAccountNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecondaryAccountNumberActionPerformed

    private void btnUploadImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadImageActionPerformed
        // TODO add your handling code here:
            
            
            JFileChooser file = new JFileChooser();
            file.setCurrentDirectory(new File(System.getProperty("user.home")));
            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
            file.addChoosableFileFilter(filter);
            int result = file.showSaveDialog(null);
            if(result == JFileChooser.APPROVE_OPTION){
                File selectedFile = file.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                person.setImgUrl(path);
                setVisible(true);
            }
                
    }//GEN-LAST:event_btnUploadImageActionPerformed

    private void btnUploadBiometricsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadBiometricsActionPerformed
        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
            file.setCurrentDirectory(new File(System.getProperty("user.home")));
            FileNameExtensionFilter filter = new FileNameExtensionFilter("*.Images", "jpg","gif","png");
            file.addChoosableFileFilter(filter);
            int result = file.showSaveDialog(null);
            if(result == JFileChooser.APPROVE_OPTION){
                File selectedFile = file.getSelectedFile();
                String path = selectedFile.getAbsolutePath();
                person.setBiometricsUrl(path);
                setVisible(true);
            }
        
        
    }//GEN-LAST:event_btnUploadBiometricsActionPerformed

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUploadBiometrics;
    private javax.swing.JButton btnUploadImage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbSSN;
    private javax.swing.JLabel lblAccountNumber;
    private javax.swing.JLabel lblCert_LicenceNo;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDeviceIdenNumber;
    private javax.swing.JLabel lblEmailID;
    private javax.swing.JLabel lblFax;
    private javax.swing.JLabel lblGeogDate;
    private javax.swing.JLabel lblHealthPlanID;
    private javax.swing.JLabel lblIPAddr;
    private javax.swing.JLabel lblIdentifierNo;
    private javax.swing.JLabel lblLinkedin;
    private javax.swing.JLabel lblMRN;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblTelNo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleIden_SerialNo;
    private javax.swing.JTextField txtCert_LicenceNo;
    private com.toedter.calendar.JDateChooser txtDOB;
    private javax.swing.JTextField txtDeviceIdenNumber;
    private javax.swing.JTextField txtDeviceIdenNumber2;
    private javax.swing.JTextField txtFax;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtGeogData;
    private javax.swing.JTextField txtHealthPlanID;
    private javax.swing.JTextField txtIPAddr1;
    private javax.swing.JTextField txtIPAddr2;
    private javax.swing.JTextField txtIdentifierNo;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtLinkedin;
    private javax.swing.JTextField txtMRN;
    private javax.swing.JTextField txtPrimaryAccountNumber;
    private javax.swing.JTextField txtPrimaryEmailID;
    private javax.swing.JTextField txtPrimaryNo;
    private javax.swing.JTextField txtSSN;
    private javax.swing.JTextField txtSecondaryAccountNumber;
    private javax.swing.JTextField txtSecondaryEmailID;
    private javax.swing.JTextField txtSecondaryNo;
    private javax.swing.JTextField txtVehicleIden_SerialNo;
    // End of variables declaration//GEN-END:variables
}
